# -*- coding: utf-8 -*-
"""RandomTextCapitalizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8ncOyv9HME3hVHZ5QT7uQD0Fd10OQOg
"""

import random

def mocking_tone(str_input):
  ret_str = ""
  for i in range(0, len(str_input)):

    # get a random floating point number to serve as a "flag" for whether or not
    # the input string's case should be changed
    randnum = random.random()

    if(randnum >= 0.578 and str_input[i].isalpha()):
      if str_input[i].islower():
        ret_str+= str_input[i].upper()
      elif str_input[i].isupper():
        ret_str+= str_input[i].lower()

    else:
      ret_str+= str_input[i]

  return ret_str

def main():
  instr = "yeet"
  while(instr != "q"):
    print("Type your text here (type q to quit): ")
    instr = input()

    if(instr != "q"):
      print(mocking_tone(instr))

if __name__ == "__main__":
  main()
